
#r "nuget: FSharp.Control.AsyncSeq"
#r "nuget: FSharp.SystemTextJson"
#r "nuget: Microsoft.Extensions.Configuration"
#r "nuget: Microsoft.Extensions.Configuration.Abstractions"
#r "nuget: Microsoft.Extensions.Hosting"
#r "nuget: Microsoft.Extensions.Logging"
#r "nuget: Microsoft.Extensions.Logging.Console" 
#r "nuget: Microsoft.SemanticKernel.Core"
#r "nuget: SkiaSharp, 2.88.9" 
#r "nuget: System.Text.Json"
#r "nuget: Microsoft.Playwright"
#r "nuget: System.Drawing.Common"
#r "nuget: System.Management"
#r "nuget: System.Net.Http"
#r "nuget: System.Text.RegularExpressions"
#r "nuget: Microsoft.SemanticKernel"
#r "nuget: Microsoft.SemanticKernel.Plugins.Core, 1.57.0-preview"

//#r "nuget: WindowsInput"

#r @"..\..\RTOpenAI.Api\bin\Debug\net9.0-windows10.0.19041.0\RTOpenAI.Api.dll"
#r @"..\..\FsResponses\bin\Debug\net9.0\FsResponses.dll"


#load "..\Misc\Constants.fs"
#load "..\Misc\Log.fs"
#load "..\Misc\Utils.fs"

#load "..\UIDrivers\UITypes.fs"
//#load "..\UIDrivers\NativeDriver.fs" 
#load "..\UIDrivers\PlaywrightDriver.fs"


#load "..\Misc\Constants.fs"
#load "..\Misc\Log.fs"
#load "..\Misc\Utils.fs"
#load "..\UIDrivers\UITypes.fs"
#load "..\UIDrivers\NativeDriver.fs"
#load "..\UIDrivers\PlaywrightDriver.fs"
#load "..\Flows\Prompts.fs"
#load "..\Flows\Actions.fs"
#load "..\Flows\Bus.fs"
#load "..\Flows\Workflow.fs"
#load "..\Flows\ChatMsg.fs"
#load "..\Flows\Functions.fs"
#load "..\Flows\Toolbox.fs"
#load "..\Flows\FlowsCommon.fs"
#load "..\Flows\TaskState.fs"
#load "..\Flows\Reasoner.fs"
#load "..\Flows\Cua.fs"
#load "..\Flows\Voice.fs"
#load "..\Flows\Dynamic\Dynamic_Messages.fs"
#load "..\Flows\Dynamic\Reasoner_Dynamic.fs"
#load "..\Flows\Dynamic\Cua_Dynamic.fs"
#load "..\Flows\Dynamic\TaskFlow_Dynamic.fs"
#load "..\Flows\Dynamic\_TaskFlowDynamic.fs"
#load "..\Flows\OTask.fs"
#load "..\Flows\OPlan.fs"
