<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsWindows>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))</IsWindows>
		<IsOSX>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))</IsOSX>
		<IsLinux>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))</IsLinux>
		<TargetFrameworks></TargetFrameworks>
		<TargetFrameworks Condition="$(IsOSX)">net9.0;$(TargetFrameworks)</TargetFrameworks>
		<TargetFrameworks Condition="$(IsWindows)">net9.0-windows10.0.19041.0;$(TargetFrameworks)</TargetFrameworks>
		<TargetFrameworks Condition="$(IsLinux)">net9.0;$(TargetFrameworks)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<None Include="scripts\packages.fsx" />
		<None Include="scripts\testPromptSerialization.fsx" />
		<Compile Include="Misc\Constants.fs" />
		<Compile Include="Misc\Log.fs" />
		<Compile Include="Misc\Utils.fs" />
		<Compile Include="UIDrivers\UITypes.fs" />
		<Compile Include="UIDrivers\NativeDriver.fs" />
		<Compile Include="UIDrivers\PlaywrightDriver.fs" />
		<Compile Include="Flows\Prompts.fs" />
		<Compile Include="Flows\Actions.fs" />
		<Compile Include="Flows\Bus.fs" />
		<Compile Include="Flows\Workflow.fs" />
		<Compile Include="Flows\ChatMsg.fs" />
		<Compile Include="Flows\Functions.fs" />
		<Compile Include="Flows\Schema.fs" />
		<Compile Include="Flows\Toolbox.fs" />
		<Compile Include="Flows\FlowsCommon.fs" />
		<Compile Include="Flows\TaskState.fs" />
		<Compile Include="Flows\Reasoner.fs" />
		<Compile Include="Flows\Cua.fs" />
		<Compile Include="Flows\Voice.fs" />
		<Compile Include="Flows\Dynamic\Dynamic_Messages.fs" />
		<Compile Include="Flows\Dynamic\Reasoner_Dynamic.fs" />
		<Compile Include="Flows\Dynamic\Cua_Dynamic.fs" />
		<Compile Include="Flows\Dynamic\TaskFlow_Dynamic.fs" />
		<Compile Include="Flows\Dynamic\_TaskFlowDynamic.fs" />
		<Compile Include="Flows\Interactive\Interactive_Messages.fs" />
		<Compile Include="Flows\Interactive\Cua_Interactive.fs" />
		<Compile Include="Flows\Interactive\Reasoner_Interactive.fs" />
		<Compile Include="Flows\Interactive\TaskFlow_Interactive.fs" />
		<Compile Include="Flows\OTask.fs" />
		<Compile Include="Flows\OPlan.fs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FSharp.Control.AsyncSeq" Version="3.2.1" />
		<PackageReference Include="FSharp.SystemTextJson" Version="1.4.36" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
		<PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.63.0" />
		<PackageReference Include="Microsoft.SemanticKernel.Plugins.Core" Version="1.57.0-preview" />
		<PackageReference Include="SkiaSharp" Version="3.119.0" />
		<PackageReference Include="System.Text.Json" Version="9.0.8" />
		<PackageReference Include="Microsoft.Playwright" Version="1.54.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FsResponses\FsResponses.fsproj" />
		<ProjectReference Include="..\RTOpenAI.Api\RTOpenAI.Api.fsproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0' OR '$(TargetFramework)' == 'net8.0-windows10.0.17763.0' ">
		<ProjectReference Include="..\FsOpWinDriver\FsOpWinDriver.fsproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="FSharp.Core" Version="9.0.303" />

	</ItemGroup>

</Project>