module SpreadsheetToEmailPlan
open FsOpCore
open System.Text.Json
open Microsoft.SemanticKernel

let tGetEmails =
    { OTask.Create() with
        id = "get_emails"
        description = "Get emails ids from Excel"
        target = OLink "https://tmobileusa-my.sharepoint.com/:x:/r/personal/faisal_waris1_t-mobile_com/_layouts/15/Doc.aspx?sourcedoc=%7B24864620-6e64-454e-a50c-9bf02f98761c%7D&action=edit&wdPreviousSession=bc554659-d29a-64c8-7b5b-ca6e932a7d3c"
        tools = FlUtils.makeFunctionTools<OPlanMemory>() @ FlUtils.makeFunctionTools<Navigator>()
        reasoner = Some Prompts.``reasoner prompt for cua guidance``
        cua = Some """You goal is to note down the names and email ids of persons in the Excel sheet and save them to memory for the next task. Scroll as need to get all the data.
Note: If needed, use Faisal.Waris1@t-mobile.com as login email id.
"""
        }

let tSendEmails =
    { OTask.Create() with
        id = "send_emails"
        description = "Send emails"
        target = OLink "https://outlook.office.com/mail/"
        tools = FlUtils.makeFunctionTools<OPlanMemory>() @ FlUtils.makeFunctionTools<Navigator>()
        reasoner = Some Prompts.``reasoner prompt for cua guidance``
        cua = Some """
Obtain the names and email address of all contacts from memory (use get_memory).

For each contact:
1. Compose a new email by using the 'New mail' button
2. Enter the 'to' email address. Use 'tab' to accept the email suggestion or click on the suggestion.
3. Subject: 'Hello from Cua'
4. Body:
```Dear <contact name>,
This is an email generated by the Cua agent. 
Please ignore.
Sincerely,
Cua model
```
5. Click "Send" to send the mail

Notes: 
    - If needed, use Faisal.Waris1@t-mobile.com as login email id.
    - Dismiss any reminders and pop ups, if requried.
    - Use 'home' function to get back to main page
    - To focus the 'body' field. Just tell CUA to 'click in the Body area'

Tasks ends when all emails have been sent.


"""
        }

let create() =
        let plan =
            { OPlan.Default with
                description = "Take contacts from Excel and send email"
                root = ONode.Seq {nodes= [ONode.Leaf tGetEmails; ONode.Leaf tSendEmails]; description=None}
                //root = ONode.All {nodes= [ONode.One tSendEmails]; description=None}
            }
        plan

let memSnapshot_tSendEmails = """
{
  "Faisal Waris": [
    "Faisal.Waris1@t-mobile.com"
  ],
  "Numan Suri": [
    "Numan.Suri1@t-mobile.com"
  ]
}
"""

let testKernel nav =
    let b = Kernel.CreateBuilder()
    //b.Plugins.AddFromType<OPlanMemory>() |> ignore
    let mem = OPlanMemory()
    let memD = JsonSerializer.Deserialize<Map<string,string list>>(memSnapshot_tSendEmails)
    mem.SetMemory(memD)
    b.Plugins.AddFromObject(mem) |> ignore
    //b.Plugins.AddFromObject(OPlanMemory.LoadState()) |> ignore
    b.Plugins.AddFromObject(nav) |> ignore
    b.Build()
