module SpreadsheetToEmailPlan
open FsOpCore

let tGetEmails =
    { OTask.Create() with
        id = "get_emails"
        description = "Get emails ids from Excel"
        target = OLink "https://tmobileusa-my.sharepoint.com/:x:/r/personal/faisal_waris1_t-mobile_com/_layouts/15/Doc.aspx?sourcedoc=%7B24864620-6e64-454e-a50c-9bf02f98761c%7D&action=edit&wdPreviousSession=bc554659-d29a-64c8-7b5b-ca6e932a7d3c"
        tools = FlUtils.makeFunctionTools<OPlanMemory>() @ FlUtils.makeFunctionTools<Navigator>()
        reasoner = Some Prompts.``reasoner prompt for cua guidance``
        cua = Some """You goal is to note down the names and email ids of persons in the Excel sheet and save them to memory for the next task. Scroll as need to get all the data.
Note: If needed, use Faisal.Waris1@t-mobile.com as login email id.
"""
        }

let tSendEmails =
    { OTask.Create() with
        id = "send_emails"
        description = "Send emails"
        target = OLink "https://outlook.office.com/mail/"
        tools = FlUtils.makeFunctionTools<OPlanMemory>() @ FlUtils.makeFunctionTools<Navigator>()
        reasoner = Some Prompts.``reasoner prompt for cua guidance``
        cua = Some """
Obtain the names and email address of all contacts from memory (use dump_memory).

For each contact:
1. Compose a new email
2. Enter the email address
3. Enter the subject 'Hello from Cua'
4. Enter the body as:
```Dear <contact name>,
This is an email generated by the Cua agent. 
Please ignore.
Sincerely,
Cua model
```

Notes: 
    - If needed, use Faisal.Waris1@t-mobile.com as login email id.
    - Dismiss any reminders and pop ups, if requried.

Tasks ends when all emails have been sent.


"""
        }

let create() =
        let plan =
            { OPlan.Default with
                description = "Take contacts from Excel and send email"
                //root = ONode.All {nodes= [ONode.One tHours; ONode.One tCapability; ONode.One t_tTime]; description=None}
                //root = ONode.All {nodes= [ONode.One tCapability; ONode.One t_tTime]; description=None}
                root = ONode.All {nodes= [ONode.One tGetEmails; ONode.One tSendEmails]; description=None}
            }
        plan



