module SpreadsheetToEmailPlan
open FsOpCore
open System.Text.Json
open Microsoft.SemanticKernel

let link,login = 
    if false then 
        "https://excel.cloud.microsoft/open/onedrive/?docId=932B65600EEDADE8%21s004ffc0fd572449793439c9ead82dec2&driveId=932B65600EEDADE8",
        "FaisalWaris@live.com"
    else
        "https://tmobileusa-my.sharepoint.com/:x:/r/personal/faisal_waris1_t-mobile_com/_layouts/15/Doc.aspx?sourcedoc=%7B24864620-6e64-454e-a50c-9bf02f98761c%7D&action=edit&wdPreviousSession=bc554659-d29a-64c8-7b5b-ca6e932a7d3c",
        "Faisal.Waris1@t-mobile.com"

let tGetEmails =
    { OTask.Create() with
        id = "get_emails"
        description = "Get emails ids from Excel"
        target = OLink $"{link}"
        tools = Toolbox.tools [
                    typeof<Functions.FsOpMemory>
                    typeof<Functions.FsOpNavigator>
                    typeof<Functions.FsOpTaskTools>
                ]
        reasoner = Some Prompts.``reasoner prompt for cua guidance``
        cua = Some $"""You goal is to note down the names and email ids of persons in the Excel sheet and save them to memory for the next task. Scroll as need to get all the data.
Note: If required, use {login} as login email id.
"""
        }

let tSendEmails =
    { OTask.Create() with
        id = "send_emails"
        description = "Send emails"
        target = OLink "https://outlook.office.com/mail/"
        tools = Toolbox.tools [
                    typeof<Functions.FsOpMemory>
                    typeof<Functions.FsOpNavigator>
                    typeof<Functions.FsOpTaskTools>
                ]
        reasoner = Some Prompts.``reasoner prompt for cua guidance``
        cua = Some $"""
Obtain the names and email address of all contacts from memory (use memory_get_all).

For each contact:
1. Compose a new email by using the 'New mail' button
2. Enter the 'to' email address. Use 'tab' to accept the email suggestion or click on the suggestion.
3. Subject: 'Hello from Cua'
4. Focus in the 'body' field. Tell CUA to click into the field below 'Hello from Cua'
5. Body:
```Dear <contact name>,
This is an email generated by the Cua agent. 
Please ignore.
Sincerely,
Cua model
```
6. Click "Send" to send the mail

Notes: 
    - If required, use {login} as login email id.
    - Dismiss any reminders and pop ups, if requried.
    - Use 'home' function to get back to main page
    - To clear a field, you can as Cua to issue 'CTRL-A' and then 'Delete' key.

Tasks ends when all emails have been sent.


"""
        }

let create() =
        let plan =
            { OPlan.Default with
                description = "Take contacts from Excel and send email"
                root = ONode.Seq {nodes= [ONode.Leaf tGetEmails; ONode.Leaf tSendEmails]; description=None}
                //root = ONode.All {nodes= [ONode.One tSendEmails]; description=None}
            }
        plan

let memSnapshot_tSendEmails = """
{
  "Faisal Waris": [
    "Faisal.Waris1@t-mobile.com"
  ],
  "Numan Suri": [
    "Numan.Suri1@t-mobile.com"
  ]
}
"""

